# Datasets to use for the benchmark
datasets: ["Visium_HD_HPC"] #, "MERFISH_mColon" , "Slideseq2_HPC" ,"CosMx_HFC"] #, "STARmap_plus_HPC"]

semiSimulation:
    FC: [1] # Fold change parameter. Is used to multiply the estimated mean in the NB sampling. Currently not used as spatial transcriptomics data is very sparse by default
    FC_nSenderCells: [1,2,3,5,7] # FC of Sender cells whose ligand expression will be added. Fraction of cells is calculated average_percentageCells_expressingLR * FC_nSenderCells * Number of sending cells
    FC_nReceiverCells: [1,2,3,5,7] # FC of Receiver cells whose receptor expression will be added. Number of cells is calculated average_percentageCells_expressingLR * FC_nReceiverCells * Number of receiver cells

# Ligand-receptor database to use -> comes from liana. More info can be found in data/InfoAbout_LR_database file
LR_database: "data/LR_database.tsv"

# This is the maximum amount of receiver cells neighbors that will be considered to add signal to.
# 1 means we just want closes neighbor. For now, values above 1 will give in error
max_N_neighbors: [1]

# Index of ligand receptor pairs to inflate expression
# We are simulating LR pairs separately because the spatial transcriptomics data is already sparse and we dont want to change data properties by simulating many LR pairs at the same time
# the results of different indexLR are aggregated
indexLR_toSample: [1,2,3,4,5] #,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50]

# Methods to use in the benchmark
methods: ["giotto" , "seurat_wilcoxon" , "NICHES", "lianaP_morans", "mistyR" ,"cellphonedb", "cellchat","stlearn"] # "lianaP_lee"

l_param_index: [0,1,2] # index to subset python dict -> this indicates how many different l parameteres we want to test

# Methods have a way to compute distances around cells of interest. THis can be euclidean distance, gaussian kernel, rbf kernel etc... l_param represents distances
# Unfortunately the distances are different depending on the method
l_param:
  lianaP:
    STARmap_plus_HPC: [300,500,700]
    CosMx_HFC: [100,200,300]
    Slideseq2_HPC: [40,60,80] 
    MERFISH_mColon: [20,40,60]
    Visium_HD_HPC: [100,200,300]
  NICHES:
    STARmap_plus_HPC: [300,500,700]
    CosMx_HFC: [100,200,300]
    Slideseq2_HPC: [40,60,80] 
    MERFISH_mColon: [20,40,60]
    Visium_HD_HPC: [100,200,300]
  CellChat:
    STARmap_plus_HPC: [300,500,700]
    CosMx_HFC: [100,200,300]
    Slideseq2_HPC: [40,60,80] 
    MERFISH_mColon: [20,40,60]
    Visium_HD_HPC: [100,200,300]
  giotto:
    STARmap_plus_HPC: [300,500,700]
    CosMx_HFC: [100,200,300]
    Slideseq2_HPC: [40,60,80] 
    MERFISH_mColon: [20,40,60]
    Visium_HD_HPC: [100,200,300]
  stlearn:
    STARmap_plus_HPC: [300,500,700]
    CosMx_HFC: [100,200,300]
    Slideseq2_HPC: [40,60,80] 
    MERFISH_mColon: [20,40,60]
    Visium_HD_HPC: [100,200,300]
    
